DEBUG = TRUE

!IF "$(DEBUG)" == "TRUE"
COPT = /c /W3 /AL /Od /Zip /nologo
LOPT = /CO/NOLOGO/NOE/St:18000
LIBS = GnuLibDR
EXCP = rem
!ELSE
COPT = /c /W3 /AL /Ox /Grs /Zp /nologo
LOPT = /E/F/PACKC/NOLOGO/NOE/St:18000
LIBS = GnuLibOR
EXCP = pklite -p
!ENDIF

PROG = test

all : $(PROG).exe

$(PROG).obj : $(PROG).c
  cl $(COPT) $*.c

readebl.obj: readebl.c
  cl $(COPT) $*.c

wineblib.obj: wineblib.c
  cl $(COPT) $*.c

$(PROG).exe : $(PROG).obj readebl.obj wineblib.obj
  link $* readebl wineblib $(LOPT),,NUL,$(LIBS);
  $(EXCP) $(@B).EXE
